version: '3'

services:
  drupalweb:
    image: drupal:8-apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    
  postgresdb:
    image: postgres:10
    environment:
      POSTGRES_DB: drupaldb
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupalpass
    restart: always
